#!/usr/bin/env node
/**
 * Cross-link strip for the sibling GitHub Pages sites.
 *
 * Reads data/profile.json, keeps project entries published as repo Pages sites
 * (host xpressabhi.github.io, /<repo>/ paths only — not subpages of the
 * portfolio itself), in profile order, and renders a one-line footer strip
 * linking each site plus a deep link back to the portfolio's #projects hub.
 * The portfolio is the single source of truth: no second list to drift.
 *
 * Usage:
 *   node scripts/projects-bar.mjs                 # writes output/projects-bar.html
 *   node scripts/projects-bar.mjs --current ordo  # that site renders as plain text
 *
 * Paste the strip inside each site's footer (see docs/superpowers/specs/
 * 2026-10-09-github-pages-linking-design.md).
 */
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const HUB = "https://xpressabhi.github.io/#projects";
const ACCENT = ' style="color:var(--accent, inherit)"';

/** True for Pages repo sites (xpressabhi.github.io/<repo>/), false for the hub itself and subpages. */
export function isPagesSite(url) {
  try {
    const u = new URL(url);
    return u.host === "xpressabhi.github.io" && /^\/[^/]+\/$/.test(u.pathname);
  } catch {
    return false;
  }
}

/** @param {Array<{name:string,url:string}>} projects @param {{current?:string,hub?:string}} [opts] */
export function renderProjectsBar(projects, opts = {}) {
  const { current, hub = HUB } = opts;
  const sites = projects.filter((p) => p.url && isPagesSite(p.url));
  const links = sites.map((p) =>
    p.name === current
      ? `<span aria-current="page">${p.name}</span>`
      : `<a href="${p.url}"${ACCENT}>${p.name}</a>`
  );
  links.push(`<a href="${hub}"${ACCENT}>portfolio →</a>`);
  return `More by Abhishek Maurya · ${links.join(" · ")}`;
}

/* CLI -------------------------------------------------------------------- */
const argv = process.argv.slice(2);
const currentFlag = argv.indexOf("--current");
const current = currentFlag !== -1 ? argv[currentFlag + 1] : undefined;

const profile = JSON.parse(readFileSync(join(ROOT, "data/profile.json"), "utf8"));
const strip = renderProjectsBar(profile.projects ?? [], { current });
const page = `<!-- generated by scripts/projects-bar.mjs — paste into this site's footer, do not hand-edit -->
<p class="projects-bar">${strip}</p>
`;

const out = join(ROOT, "output", "projects-bar.html");
mkdirSync(join(ROOT, "output"), { recursive: true });
writeFileSync(out, page, "utf8");
console.log(`✓ strip (${current ? `current=${current}` : "no current site"}) → ${out}`);
